# Generated by Django 5.0.6 on 2026-04-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adoptionrequest",
            unique_together=set(),
        ),
    ]
