# Generated by Django 5.0.6 on 2026-04-05 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("bootcamps", "0003_bootcamp_capacity"),
        ("pets", "0005_pet_birth_date_healthrecord_reminder_sent"),
        ("shelters", "0004_shelter_latitude_shelter_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="bootcamp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bootcamps.bootcamp",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="pets.pet",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="shelters.service",
            ),
        ),
    ]
