# Generated by Django 6.0.3 on 2026-04-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_bootcamp_alter_booking_pet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
