# Generated by Django 5.0.6 on 2026-03-30 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("adoption_request", "Adoption Request"),
                            ("adoption_accepted", "Adoption Accepted"),
                            ("adoption_rejected", "Adoption Rejected"),
                            ("booking_request", "Booking Request"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_rejected", "Booking Rejected"),
                            ("booking_completed", "Booking Completed"),
                            ("payment_received", "Payment Received"),
                            ("vaccine_reminder", "Vaccine Reminder"),
                            ("system", "System Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("action_url", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
