# Generated by Django 5.0.6 on 2026-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_admin_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("adoption_request", "Adoption Request"),
                    ("adoption_accepted", "Adoption Accepted"),
                    ("adoption_rejected", "Adoption Rejected"),
                    ("booking_request", "Booking Request"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_rejected", "Booking Rejected"),
                    ("booking_completed", "Booking Completed"),
                    ("payment_received", "Payment Received"),
                    ("vaccine_reminder", "Vaccine Reminder"),
                    ("order_deleted", "Order Deleted"),
                    ("system", "System Notification"),
                    ("admin_message", "Message from Admin"),
                    ("co_admin_message", "Message from Co-Admin"),
                ],
                max_length=30,
            ),
        ),
    ]
