# Generated by Django 5.0.6 on 2026-03-30 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=300)),
                ("address", models.TextField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="shelters/"),
                ),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("boarding", "Boarding"),
                            ("grooming", "Grooming"),
                            ("vaccination", "Vaccination"),
                            ("training", "Training"),
                            ("daycare", "Day Care"),
                            ("veterinary", "Veterinary"),
                            ("bath", "Bath & Spa"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_unit", models.CharField(default="per day", max_length=20)),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Typical duration in days"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="shelters.shelter",
                    ),
                ),
            ],
            options={
                "ordering": ["service_type", "price"],
            },
        ),
    ]
