# Generated by Django 5.0.6 on 2026-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0, help_text="Percentage discount (0-100)"
            ),
        ),
    ]
