# Generated by Django 5.0.6 on 2026-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_service_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
