# Generated by Django 5.0.6 on 2026-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_shelter_latitude_shelter_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="capacity",
            field=models.PositiveIntegerField(
                default=10, help_text="Maximum concurrent bookings for this service"
            ),
        ),
    ]
