# Generated by Django 5.0.6 on 2026-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="reset_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
