# Generated by Django 5.0.6 on 2026-04-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_latitude_customuser_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Pet Owner"),
                    ("shelter_staff", "Shelter Staff"),
                    ("seller", "Pet Product Seller"),
                    ("admin", "Admin"),
                ],
                default="owner",
                max_length=20,
            ),
        ),
    ]
