# Generated by Django 5.0.6 on 2026-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="identity_document",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
