# Generated by Django 5.0.6 on 2026-04-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_identity_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="identity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nid", "NID"),
                    ("tin", "TIN"),
                    ("brn", "BRN"),
                    ("tl", "Trade License"),
                ],
                default="nid",
                max_length=10,
            ),
        ),
    ]
