# Generated by Django 6.0.3 on 2026-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_identity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_password_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
