# Generated by Django 5.0.6 on 2026-04-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_avatar_historicalcustomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Pet Owner'), ('shelter_staff', 'Shelter Staff'), ('seller', 'Pet Product Seller'), ('admin', 'Admin'), ('doctor', 'Veterinary Doctor')], default='owner', max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
    ]
