# Generated by Django 5.0.6 on 2026-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role_delete_historicalcustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
