# Generated by Django 5.0.6 on 2026-04-01 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shelters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bootcamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "bootcamp_type",
                    models.CharField(
                        choices=[
                            ("training", "Pet Training"),
                            ("breeding", "Breeding Program"),
                            ("vaccination", "Vaccination Drive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="marked_bootcamps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bootcamps",
                        to="shelters.shelter",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
