# Generated by Django 5.0.6 on 2026-04-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bootcamp",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
