# Generated by Django 5.0.6 on 2026-04-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamps", "0002_bootcamp_is_paid_bootcamp_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="capacity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
