# Generated by Django 5.0.6 on 2026-04-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvc_number', models.CharField(help_text='Format: BVC-REG-DHK-07892-23 or BVC-PROV-CHT-45123-22', max_length=30, unique=True)),
                ('bvc_type', models.CharField(choices=[('REG', 'Regular License'), ('PROV', 'Provisional License')], default='REG', max_length=10)),
                ('division_code', models.CharField(choices=[('DHK', 'Dhaka (DHK)'), ('CHT', 'Chattogram (CHT)'), ('RAJ', 'Rajshahi (RAJ)'), ('KHL', 'Khulna (KHL)'), ('BAR', 'Barishal (BAR)'), ('SYL', 'Sylhet (SYL)'), ('RAN', 'Rangpur (RAN)'), ('MYM', 'Mymensingh (MYM)')], default='DHK', max_length=5)),
                ('is_bvc_verified', models.BooleanField(default=False, help_text='Manually set by admin after confirming with BVC authority.')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, choices=[('general', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('surgery', 'Surgery'), ('dentistry', 'Dentistry'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('exotic', 'Exotic Animals'), ('avian', 'Avian (Birds)'), ('aquatic', 'Aquatic Animals'), ('other', 'Other')], default='general', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee per consultation in BDT', max_digits=8, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('clinic_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
