# Generated by Django 5.0.6 on 2026-04-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short description of the blog post')),
                ('content', models.TextField(help_text='Main content of the blog post')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='health_blogs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Blog',
                'verbose_name_plural': 'Health Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
