# Generated by Django 5.0.6 on 2026-04-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_emergencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='EmergencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='emergency_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='veterinary.emergencyrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
