# Generated by Django 5.0.6 on 2026-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_emergencyrequest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='emergency_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for emergency service in BDT', max_digits=8, null=True),
        ),
    ]
