# Generated by Django 5.0.6 on 2026-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0006_doctorprofile_emergency_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
