# Generated by Django 6.0.3 on 2026-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='selected_consultation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
