# Generated by Django 6.0.3 on 2026-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0009_doctorprofile_selected_consultation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
