# Generated by Django 5.0.6 on 2026-04-06 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Login email for the group portal.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Stored as a bcrypt/PBKDF2 hash — never plain-text.",
                        max_length=255,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The Django auth Group that determines this member's permissions.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_members",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Member",
                "verbose_name_plural": "Group Members",
                "ordering": ["group__name", "email"],
            },
        ),
        migrations.CreateModel(
            name="GroupMemberActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Human-readable description of the action taken.",
                        max_length=255,
                    ),
                ),
                (
                    "permission_codename",
                    models.CharField(
                        blank=True,
                        help_text="Permission codename that enabled this action.",
                        max_length=100,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="group_portal.groupmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Activity",
                "verbose_name_plural": "Member Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
