# Generated by Django 5.0.6 on 2026-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="portal_password",
            field=models.CharField(
                blank=True,
                help_text="Plain text password (Visible to Admin)",
                max_length=128,
                verbose_name="Password",
            ),
        ),
    ]
