# Generated by Django 5.0.6 on 2026-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_portal", "0002_groupmember_portal_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmemberactivity",
            name="is_deleted_by_user",
            field=models.BooleanField(
                default=False,
                help_text="If True, hide from the user but keep for admin auditing.",
            ),
        ),
    ]
