# Generated by Django 5.0.6 on 2026-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_portal", "0003_groupmemberactivity_is_deleted_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo for the group portal.",
                null=True,
                upload_to="portal_profiles/",
            ),
        ),
    ]
