# Generated by Django 5.0.6 on 2026-04-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("group_portal", "0004_groupmember_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_for_admin",
                    models.BooleanField(
                        default=False,
                        help_text="If True, message is sent to the site administrators",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Broadcast to entire group",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_group_messages",
                        to="auth.group",
                    ),
                ),
                (
                    "recipient_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct message to member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_received_messages",
                        to="group_portal.groupmember",
                    ),
                ),
                (
                    "sender_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member sender",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_sent_messages",
                        to="group_portal.groupmember",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin sender",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Message",
                "verbose_name_plural": "Portal Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
