# Generated by Django 5.0.6 on 2026-04-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("group_portal", "0005_portalmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portalmessage",
            name="recipient_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner", "Pet Owner"),
                    ("shelter_staff", "Shelter Staff"),
                    ("seller", "Pet Product Seller"),
                ],
                help_text="Broadcast to all users with this role",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="portalmessage",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct message to main site user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="portalmessage",
            name="recipient_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Broadcast to portal group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_group_messages",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="portalmessage",
            name="recipient_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct message to portal member",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_received_messages",
                to="group_portal.groupmember",
            ),
        ),
    ]
