# Generated by Django 5.0.6 on 2026-04-01 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        ("shelters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "shelter")},
        ),
        migrations.AddField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[("shelter", "Shelter Review"), ("user", "User Review")],
                default="shelter",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Has the user actually had a transaction?"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="shelters.shelter",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "shelter"), ("user", "target_user")},
        ),
    ]
