# Generated by Django 5.0.6 on 2026-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_unique_together_review_review_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviews/"),
        ),
    ]
