# Generated by Django 5.0.6 on 2026-04-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
