# Generated by Django 5.0.6 on 2026-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("shelter", "Shelter Review"),
                    ("user", "User Review"),
                    ("platform", "Platform Review"),
                ],
                default="shelter",
                max_length=10,
            ),
        ),
    ]
