# Generated by Django 5.0.6 on 2026-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_add_platform_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('shelter', 'Shelter Review'), ('user', 'User Review'), ('doctor', 'Doctor Review'), ('platform', 'Platform Review')], default='shelter', max_length=10),
        ),
    ]
