# Generated by Django 5.0.6 on 2026-04-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("payments", "0002_payment_payment_id"),
        ("products", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="products.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="bookings.booking",
            ),
        ),
    ]
