# Generated by Django 5.0.6 on 2026-04-11 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_historicalpayment'),
        ('veterinary', '0007_emergencyrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='emergency_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='veterinary.emergencyrequest'),
        ),
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
    ]
