# Generated by Django 5.0.6 on 2026-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="admin_reply",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="complaint",
            name="reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RESOLVED", "Resolved"),
                    ("DONE", "Done"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
