# Generated by Django 5.0.6 on 2026-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("food", "Food"), ("accessories", "Accessories")],
                default="food",
                max_length=20,
            ),
        ),
    ]
