# Generated by Django 5.0.6 on 2026-04-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address",
            new_name="home_address",
        ),
        migrations.AddField(
            model_name="order",
            name="road_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
