# Generated by Django 5.0.6 on 2026-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_shipping_address_order_home_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_percent",
            field=models.PositiveIntegerField(
                default=0, help_text="Tax percentage (0-100)"
            ),
        ),
    ]
