# Generated by Django 5.0.6 on 2026-04-02 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_tax_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="archived_by",
            field=models.ManyToManyField(
                blank=True, related_name="archived_orders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
