# Generated by Django 5.0.6 on 2026-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_order_archived_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
