# Generated by Django 5.0.6 on 2026-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_order_custom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dominant_color",
            field=models.CharField(
                blank=True, help_text="Hex color code", max_length=9, null=True
            ),
        ),
    ]
