# Generated by Django 5.0.6 on 2026-04-08 13:55

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_dominant_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[utils.validators.validate_image_file],
            ),
        ),
    ]
