# Generated by Django 5.0.6 on 2026-03-30 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField(help_text="Age in months")),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("rabbit", "Rabbit"),
                            ("fish", "Fish"),
                            ("reptile", "Reptile"),
                            ("hamster", "Hamster"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="pets/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("adopted", "Adopted"),
                            ("sold", "Sold"),
                            ("boarding", "Boarding"),
                            ("pending", "Pending"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("adoption", "For Adoption"), ("sale", "For Sale")],
                        default="adoption",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_vaccinated", models.BooleanField(default=False)),
                ("is_neutered", models.BooleanField(default=False)),
                ("is_microchipped", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("treatment", "Treatment"),
                            ("checkup", "Checkup"),
                            ("surgery", "Surgery"),
                            ("medication", "Medication"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("vet_name", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
