# Generated by Django 5.0.6 on 2026-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "Dollar ($)"),
                    ("BDT", "BDT (৳)"),
                    ("EUR", "Euro (€)"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
