# Generated by Django 5.0.6 on 2026-04-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_pet_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("unavailable", "Unavailable"),
                    ("adopted", "Adopted"),
                    ("sold", "Sold"),
                    ("boarding", "Boarding"),
                    ("pending", "Pending"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
